package main

import (
	"fmt"
	"sort"
	"strings"

	"eve-cyno.dev/go/data/abyss"
)

// docDate turns the date suffix of an SDE build id ("3586130_20261007") into "2026-10-07".
// The doc carries no wall-clock time so regeneration stays deterministic.
func docDate(build string) string {
	i := strings.LastIndex(build, "_")
	if i < 0 || len(build)-i-1 != 8 {
		return build
	}
	d := build[i+1:]
	return d[:4] + "-" + d[4:6] + "-" + d[6:]
}

func thousands(v float64) string {
	s := fmt.Sprintf("%.0f", v)
	neg := strings.HasPrefix(s, "-")
	s = strings.TrimPrefix(s, "-")
	var b strings.Builder
	for i, c := range s {
		if i > 0 && (len(s)-i)%3 == 0 {
			b.WriteByte(',')
		}
		b.WriteRune(c)
	}
	if neg {
		return "-" + b.String()
	}
	return b.String()
}

func km(m float64) string {
	if m <= 0 {
		return ""
	}
	return fmt.Sprintf("%.1f km", m/1000)
}

var effectLabel = map[string]string{
	abyss.EffWeb:               "stasis web",
	abyss.EffWarpScramble:      "warp scrambler",
	abyss.EffNeutralizer:       "energy neutralizer",
	abyss.EffTargetPainter:     "target painter",
	abyss.EffSensorDamp:        "sensor dampener",
	abyss.EffGuidanceDisruptor: "guidance disruptor",
	abyss.EffTrackingDisruptor: "tracking disruptor",
	abyss.EffRemoteArmorRepair: "remote armor repair",
	abyss.EffRemoteShieldBoost: "remote shield boost",
	abyss.EffLocalArmorRepair:  "local armor repair",
	abyss.EffLocalShieldBoost:  "local shield boost",
	abyss.EffChainLightning:    "chain lightning",
}

func describeEffect(e abyss.Effect) string {
	s := effectLabel[e.Kind]
	switch e.Kind {
	case abyss.EffWeb:
		s += fmt.Sprintf(" %.0f%%", e.Strength)
	case abyss.EffWarpScramble:
		s += fmt.Sprintf(" (%.0f point)", e.Strength)
	case abyss.EffNeutralizer:
		if e.PerSecond > 0 {
			s += fmt.Sprintf(" %.0f GJ/s", e.PerSecond)
		}
	case abyss.EffTargetPainter:
		s += fmt.Sprintf(" +%.0f%%", e.Strength)
	case abyss.EffSensorDamp:
		s += fmt.Sprintf(" %.0f%% targeting range", e.Strength)
	case abyss.EffGuidanceDisruptor:
		if e.Strength != 0 {
			s += fmt.Sprintf(" %.1f%% explosion velocity", e.Strength)
		}
	case abyss.EffRemoteArmorRepair, abyss.EffRemoteShieldBoost, abyss.EffLocalArmorRepair, abyss.EffLocalShieldBoost:
		if e.PerSecond > 0 {
			s += fmt.Sprintf(" %.0f HP/s", e.PerSecond)
		}
	}
	if r := km(e.RangeM); r != "" {
		s += " at " + r
	}
	return s
}

func describeNPC(n abyss.NPC) string {
	p := abyss.KillPriority(n)
	var b strings.Builder
	fmt.Fprintf(&b, "%s: EHP %s (shield %s / armor %s / hull %s)", n.Name, thousands(n.EHP),
		thousands(n.Shield.HP), thousands(n.Armor.HP), thousands(n.Hull.HP))
	d := n.Damage
	if d.Kind == abyss.DamageNone {
		b.WriteString("; no weapon damage")
	} else {
		fmt.Fprintf(&b, "; %.0f DPS %s %s", d.DPS, d.Dominant, d.Kind)
		if d.Kind == abyss.DamageDisintegrator {
			b.WriteString(" (base, ramps up while firing)")
		}
		if r := km(d.OptimalM); r != "" {
			fmt.Fprintf(&b, ", range %s", r)
		}
	}
	fmt.Fprintf(&b, "; %s m/s, signature %s m", thousands(n.MaxVelocity), thousands(n.SignatureRadius))
	var fx []string
	for _, e := range n.Effects {
		fx = append(fx, describeEffect(e))
	}
	if len(fx) > 0 {
		b.WriteString("; " + strings.Join(fx, ", "))
	}
	fmt.Fprintf(&b, ". Kill priority %.1f (%s).", p.Score, p.Band)
	return b.String()
}

func threats(n abyss.NPC) []string {
	var out []string
	for _, k := range []string{abyss.EffWarpScramble, abyss.EffNeutralizer, abyss.EffRemoteArmorRepair, abyss.EffRemoteShieldBoost, abyss.EffWeb} {
		if n.Has(k) {
			out = append(out, effectLabel[k])
		}
	}
	return out
}

// RenderDoc writes the RAG knowledge document from the dataset.
func RenderDoc(ds *abyss.Dataset) string {
	var b strings.Builder
	w := func(format string, a ...any) { fmt.Fprintf(&b, format, a...) }
	w("---\nsource: EVE SDE abyssal dataset\nsource_type: wiki_supplement\nurl: https://developers.eveonline.com/static-data\nchunk_by: section\n---\n\n")
	w("# Abyssal Deadspace — weather, filament tiers and NPCs (from the SDE)\n\n")
	w("Source: EVE SDE (Fenris Creations), build %s (%s). Generated by `go generate ./abyss` in the core module "+
		"from `core/abyss/abyss_data.json`. Every number is a Fenris Creations static-data value or a documented derivation of one; "+
		"the kill priorities are this project's own heuristic, not Fenris Creations data.\n\n", ds.SDEBuild, docDate(ds.SDEBuild))

	w("## Weather types and filament tiers\n\n")
	names := make([]string, 0, len(ds.Weather))
	for _, wt := range ds.Weather {
		names = append(names, fmt.Sprintf("%s (%s)", wt.Name, wt.SDEName))
	}
	w("Abyssal Deadspace has %d weather environments: %s. ", len(ds.Weather), strings.Join(names, ", "))
	w("Each Abyssal Filament sets one weather and one difficulty tier. There are %d tiers, from tier 0 to tier %d: ", len(ds.Tiers), len(ds.Tiers)-1)
	tn := make([]string, 0, len(ds.Tiers))
	for _, t := range ds.Tiers {
		tn = append(tn, fmt.Sprintf("%d %s", t.Index, t.Name))
	}
	w("%s. A filament is named \"<Tier> <Weather> Filament\", so %d tiers times %d weathers gives %d filament types.\n\n",
		strings.Join(tn, ", "), len(ds.Tiers), len(ds.Weather), len(ds.Tiers)*len(ds.Weather))
	w("The static data does not carry numeric weather modifiers: the five environment types have no attributes or effects in it, " +
		"so the resistance penalties and bonuses per weather and per tier are not stated here. " +
		"See the separate damage-profile document for the documented values. " +
		"The static data also does not say which NPCs appear in which tier or weather.\n\n")
	for _, t := range ds.Tiers {
		var fs []string
		for _, f := range t.Filaments {
			fs = append(fs, fmt.Sprintf("%s (type %d)", f.Name, f.TypeID))
		}
		w("Tier %d, %s: %s.\n", t.Index, t.Name, strings.Join(fs, "; "))
	}
	w("\n")

	if len(ds.Hazards) > 0 {
		w("## Hazard clouds\n\nThe static data has these ambient and deployable cloud types in the Abyssal Hazards group. " +
			"Buffs are raw warfare-buff ids and values; the static data does not name them.\n\n")
		for _, h := range ds.Hazards {
			s := fmt.Sprintf("%s (type %d)", h.Name, h.TypeID)
			if r := km(h.RangeM); r != "" {
				s += ", range " + r
			}
			for _, bf := range h.Buffs {
				s += fmt.Sprintf(", buff %d = %g", bf.ID, bf.Value)
			}
			w("%s.\n", s)
		}
		w("\n")
	}

	w("## Kill-priority heuristic (this project's own, not Fenris Creations')\n\n")
	w("Kill priority ranks NPCs by threat removed per unit of effort, using only static-data facts. "+
		"threat = the sum of ewar points + 40 x dps / (dps + 100). Ewar points: warp scrambler 30, remote armor repair 25, "+
		"remote shield boost 25, energy neutralizer 25, stasis web 15, tracking disruptor 12, guidance disruptor 12, "+
		"sensor dampener 10, target painter 10, chain lightning 10; local repairs score 0. "+
		"effort = 1 + square root of (EHP / 5000). score = threat / effort. "+
		"Bands: score at least %.0f is \"kill first\", at least %.0f is \"kill next\", otherwise \"kill last\". "+
		"The model ignores weather, your fit, range and tracking, disintegrator ramp-up and spawn counts, so treat it as a starting order. "+
		"DPS is the base figure from volley / cycle time; EHP treats all four damage types equally (each layer's HP divided by its mean resonance).\n\n", abyss.BandFirstMin, abyss.BandNextMin)

	byFamily := map[string][]abyss.NPC{}
	for _, n := range ds.NPCs {
		byFamily[n.Family] = append(byFamily[n.Family], n)
	}
	fams := make([]string, 0, len(byFamily))
	for f := range byFamily {
		fams = append(fams, f)
	}
	sort.Strings(fams)

	w("## NPC families\n\nThe static data lists %d NPC types in the Abyssal Spaceship Entities and Abyssal Drone Entities groups, in %d name families: %s.\n\n",
		len(ds.NPCs), len(fams), strings.Join(fams, ", "))
	for _, f := range fams {
		npcs := byFamily[f]
		w("## %s\n\n", f)
		ranked := abyss.RankByPriority(npcs)
		var key []string
		for _, r := range ranked {
			if t := threats(r.NPC); len(t) > 0 && len(key) < 6 {
				key = append(key, fmt.Sprintf("%s (%s)", r.NPC.Name, strings.Join(t, ", ")))
			}
		}
		if len(key) > 0 {
			w("Key threats in the %s family, highest kill priority first: %s.\n\n", f, strings.Join(key, "; "))
		} else {
			w("No ewar or repair threats in the %s family; the danger is damage.\n\n", f)
		}
		for _, r := range ranked {
			w("%s\n", describeNPC(r.NPC))
		}
		w("\n")
	}
	return b.String()
}
